apiVersion: v1
kind: ServiceAccount
metadata:
  name: tick-storm
  namespace: tick-storm
  labels:
    app: tick-storm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tick-storm
  name: tick-storm-role
  labels:
    app: tick-storm
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tick-storm-rolebinding
  namespace: tick-storm
  labels:
    app: tick-storm
subjects:
- kind: ServiceAccount
  name: tick-storm
  namespace: tick-storm
roleRef:
  kind: Role
  name: tick-storm-role
  apiGroup: rbac.authorization.k8s.io
