apiVersion: v1
kind: Secret
metadata:
  name: tick-storm-auth
  namespace: tick-storm
  labels:
    app: tick-storm
type: Opaque
data:
  # Base64 encoded credentials (change in production)
  # Default: admin / secure123
  username: YWRtaW4=
  password: c2VjdXJlMTIz
---
# Uncomment and configure for TLS support
# apiVersion: v1
# kind: Secret
# metadata:
#   name: tick-storm-tls
#   namespace: tick-storm
#   labels:
#     app: tick-storm
# type: kubernetes.io/tls
# data:
#   tls.crt: |
#     LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
#   tls.key: |
#     LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
