apiVersion: v1
kind: Service
metadata:
  name: tick-storm-service
  namespace: tick-storm
  labels:
    app: tick-storm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: tick-storm
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: tick-storm-headless
  namespace: tick-storm
  labels:
    app: tick-storm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tick-storm
